server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/careerwry-member
    username: careerwry
    password: 1q2w3e4r
  flyway:
    enabled: true
    baseline-on-migrate: true # // 이 시점의 DB의 DDL이나 테이블이 아예 날라가도 기록해놓아야 하는 sql을 기록
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/careerwry
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        connection:
          driver_class: com.mysql.cj.jdbc.Driver
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: true
    show-sql: true

## Logging
logging:
  level:
    org.hibernate.orm.jdbc.bind: DEBUG
